
const names = [
    "Emily",
       "David",
       "Samantha",
       "Michael",
       "Ashley",
       "Daniel",
       "Olivia",
       "Christopher",
       "Jessica",
       "Matthew",
       "Madison",
       "Joshua",
       "Sarah",
       "Ryan",
       "Emma",
       "Alexander",
       "Lauren",
       "Nathan",
       "Sophia",
       "William",
       "Isabella",
       "Ethan",
       "Ava",
       "Andrew",
       "Mia",
       "James",
       "Chloe",
       "Jacob",
       "Grace",
       "Benjamin",
       "Lily",
       "Samuel",
       "Sophia",
       "Christopher",
       "Avery",
       "Tyler",
       "Elizabeth",
       "Mason",
       "Victoria",
       "Logan",
       "Abigail",
       "Caleb",
       "Zoey",
       "Gabriel",
       "Natalie",
       "Dylan",
       "Addison",
       "Elijah",
       "Harper",
       "Luke",
       "Lillian",
       "Christian",
       "Sofia",
       "Brandon",
       "Avery",
       "Jackson",
       "Hailey",
       "Isaac",
       "Samantha",
       "Connor",
       "Evelyn",
       "Daniel",
       "Aiden",
       "Scarlett",
       "Wyatt",
       "Penelope",
       "Gavin",
       "Stella",
       "Oliver",
       "Madelyn",
       "Nicholas",
       "Layla",
       "Henry",
       "Claire",
       "Sebastian",
       "Hannah",
       "Julian",
       "Ariana",
       "Owen",
       "Riley",
       "Ellie",
       "Levi",
       "Mackenzie",
       "Carson",
       "Peyton",
       "Cooper",
       "Julia",
       "Tristan",
       "Kennedy",
       "Dominic",
       "Gabriella",
       "Jaxon",
       "Willow",
       "Jordan",
       "Piper",
       "Ayden",
       "Naomi",
       "Blake",
       "Reagan",
       "Xavier"
   ]
   
   const lastNames = [
    "Johnson",
       "Martinez",
       "Lee",
       "Brown",
       "Nguyen",
       "Jackson",
       "Garcia",
       "Kim",
       "Smith",
       "Patel",
       "Taylor",
       "Anderson",
       "Gonzalez",
       "Thomas",
       "Hernandez",
       "Wilson",
       "Davis",
       "Rodriguez",
       "Moore",
       "Lopez",
       "Thompson",
       "White",
       "Martinez",
       "Robinson",
       "Lewis",
       "Clark",
       "Walker",
       "Harris",
       "King",
       "Adams",
       "Turner",
       "Wright",
       "Hill",
       "Young",
       "Mitchell",
       "Baker",
       "Hall",
       "Green",
       "Carter",
       "Evans",
       "Rivera",
       "Phillips",
       "Scott",
       "Ramirez",
       "Price",
       "Morgan",
       "Cooper",
       "Bennett",
       "Reed",
       "Kelly",
       "Bailey",
       "Brooks",
       "Ward",
       "Ross",
       "Coleman",
       "Howard",
       "Hayes",
       "Nelson",
       "Barnes",
       "Coleman",
       "Perry",
       "Evans",
       "Rivera",
       "Patterson",
       "Simmons",
       "Murphy",
       "Perry",
       "Richardson",
       "Cox",
       "Long",
       "Hughes",
       "Wood",
       "Foster",
       "Simmons",
       "Barnes",
       "Bennett",
       "Turner",
       "Scott",
       "Martinez",
       "Johnson",
       "Morris",
       "Cook",
       "Russell",
       "Coleman",
       "Washington",
       "Butler",
       "Price",
       "Ward",
       "Sanders",
       "Fisher",
       "Watson",
       "Brooks",
       "King",
       "Reed",
       "Henderson",
       "Patel",
       "Nguyen",
       "Griffin",
       "Stewart",
       "Bell"
   ]
   
   const generatePhoneNumber = () => {
     const randomNumber = () => Math.floor(Math.random() * 100)
     return `+995 ${randomNumber()}${randomNumber()}${randomNumber()}-${randomNumber()}${randomNumber()}${randomNumber()}`
   }
   
   const shuffleArray = (array) => {
     for (let i = array.length - 1; i > 0; i--) {
       const j = Math.floor(Math.random() * (i + 1))
       [array[i], array[j]] = [array[j], array[i]]
     }
     return array
   }
   
   const generateRandomContacts = (count) => {
     const contacts = []
     const shuffledNames = shuffleArray(names)
     const shuffledLastNames = shuffleArray(lastNames)
   
     for (let i = 0; i < count; i++) {
       const fullName = `${shuffledNames[i]} ${shuffledLastNames[i]}`
       const phoneNumber = generatePhoneNumber()
       contacts.push({ fullName, phoneNumber })
     }
     return contacts
   }
   
   export default generateRandomContacts(100)
   